{% set version = "1.0.0" %}

package:
  name: plaid
  version: {{ version }}

source:
  url: https://github.com/PLAID-lib/plaid/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7a1578d90f02571a23f439bf6109e9a3af00995059b1c36fb5f84ede28adc90c

build:
  number: 1
  skip: true  # [py<311 or py>313]

outputs:
  - name: plaid
    build:
      script_env:
        - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
      script: python -m pip install . --no-deps --ignore-installed -vv
    requirements:
      host:
        - python
        - setuptools >=60
        - setuptools-scm >=8.0
        - pip
      run:
        - python
        - tqdm >=4.60,<5
        - pyyaml >=6,<7
        - pycgns-core >=6.3,<7
        - numpy >=1.0,<3
        - pydantic >=2.6,<3
        - datasets >=2.18,<6
        - zarr >=3.1,<4
    test:
      requires:
        - bash  # [unix]
        - pytest
        - muscat-core >=2.5.1
        - vtk
        - ipython
      imports:
        - plaid
      source_files:
        - tests
        - examples
        - docs
      commands:
        - python -m pytest tests --ignore=tests/types/test_cgns_types.py
        - cd examples
        - bash run_examples.sh  # [unix]
        - run_examples.bat      # [win]

  - name: plaid-viewer
    build:
      script: python -m pip install . --no-deps --ignore-installed -vv
    requirements:
      host:
        - python
        - setuptools >=60
        - setuptools-scm >=8.0
        - pip
      run:
        - python
        - {{ pin_subpackage('plaid', exact=True) }}
        - trame >=3.6,<4.0
        - trame-vtk >=2.8,<3.0
        - trame-vuetify >=2.7,<4.0
        - vtk >=9.6.1
    test:
      imports:
        - plaid.viewer

about:
  home: https://github.com/PLAID-lib/plaid
  summary: Physics Learning AI Datamodel (PLAID)
  description: |
    PLAID implements a data model tailored for AI and ML in the context of physics-based numerical simulations and modeling.
  license_family: BSD
  license: BSD-3-Clause
  license_file: LICENSE.txt
  doc_url: https://plaid-lib.readthedocs.io
  dev_url: https://github.com/PLAID-lib/plaid

extra:
  recipe-maintainers:
    - bstaber
    - casenave
    - xroynard
