{% set version = "0.1.6" %}

package:
  name: plaid
  version: {{ version }}

source:
  url: https://github.com/PLAID-lib/plaid/archive/refs/tags/{{ version }}.tar.gz
  sha256: 11bf9f222f1f3e3b9731b9fae4e0e80a0eb4e0035a32e18e9fc0600c0ccaabad  

build:
  number: 0
  skip: true  # [py<39 or py>312]
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    
  script: python -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - setuptools >=60
    - setuptools-scm >=8.0      
    - pip

  run:
    - python
    - tqdm
    - pyyaml
    - pycgns-core
    - numpy
    - matplotlib-base
    - scikit-learn
    - pydantic
    - datasets >=3.0

test:
  requires:
    - bash  # [unix]
    - pytest
    - muscat ==2.4.1
  imports:
    - plaid
  source_files:
    - tests
    - examples
  commands:
    - python -m pytest tests
    - cd examples
    - bash run_examples.sh  # [unix]
    - run_examples.bat      # [win]
    
about:
  home: https://github.com/PLAID-lib/plaid
  summary: Physics Learning AI Datamodel (PLAID)
  description: |
    PLAID implements a data model tailored for AI and ML in the context of physics-based numerical simulations and modeling.
  license_family: BSD
  license: BSD-3-Clause
  license_file: LICENSE.txt
  doc_url: https://plaid-lib.readthedocs.io
  dev_url: https://github.com/PLAID-lib/plaid

extra:
  recipe-maintainers:
    - bstaber
    - casenave
    - xroynard
