{% set version = "0.1.5" %}
{% set python_min = "3.11" %}

package:
  name: plaid
  version: {{ version }}

source:
  url: https://github.com/PLAID-lib/plaid/archive/refs/tags/{{ version }}.tar.gz
  sha256: e88cef050fdf417592a647ab1a8c040c87fdcce8fa795bdd7e5610b5a2c21c79  

build:
  skip: true  # [py<311 or py>312]
  number: 1

outputs:
  - name: plaid
    build:
      script_env:
        - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    
      script: python -m pip install . -vv  
      
    requirements:
      host:
        - python {{ python_min }}
        - setuptools >=60
        - setuptools-scm >=8.0      
        - pip
    
      run:
        - python >={{ python_min }}
        - tqdm
        - pyyaml
        - pycgns-core
        - numpy
        - matplotlib-base
        - scikit-learn
        - pydantic
        - datasets >=3.0
    
    test:
      requires:
        - bash  # [unix]
        - pytest
        - muscat ==2.4.1
      imports:
        - plaid
      source_files:
        - tests
        - examples
      commands:
        - python -m pytest tests
        - cd examples
        - bash run_examples.sh  # [unix]
        - run_examples.bat      # [win]

  - name: plaid-devenv
      
    requirements:
      run:
      - python >={{ python_min }}
      - tqdm
      - pyyaml
      - pycgns-core
      - scikit-learn
      - datasets >=3.0
      - numpy
      - matplotlib-base
      - pydantic
      - muscat ==2.4.1
      - pytest
      - pytest-cov
      - ruff
      - pre-commit
      - sphinx
      - sphinx-autoapi
      - sphinx-tabs
      - sphinxcontrib-bibtex
      - myst-nb
      - myst-parser
      - furo
  
    test:
      commands:
        - python --version
    
about:
  home: https://github.com/PLAID-lib/plaid
  summary: 'Physics Learning AI Datamodel (PLAID)'
  description: |
    A package that implements a data model tailored for AI and ML in the context of physics problems

  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://plaid-lib.readthedocs.io
  dev_url: https://github.com/PLAID-lib/plaid

extra:
  recipe-maintainers:
    - bstaber
    - casenave
    - xroynard
