github:
  branch_name: main
  tooling_branch_name: main

conda_forge_output_validation: true

provider:
  linux_64: azure
  win_64: azure
  osx_64: azure

test_on_native_only: true  # optional optimization