github:
  branch_name: main
  tooling_branch_name: main

conda_forge_output_validation: true

provider:
  linux_64: azure
  win_64: azure
  osx_64: azure

test: native_and_emulated

outputs:
  - name: plaid
  - name: plaid-devenv
